version: '3.4'

services:

  data-server:
    image: "nsidc/noaa-web-server:${SERVER_VERSION:-latest}"
    volumes:
      - "/projects/DATASETS/NOAA:/usr/share/nginx/html/NOAA:ro" 
      - "/projects/DATASETS/nsidc0008_HARA_arctic_sounding_v01/DATA:/usr/share/nginx/html/nsidc-0008:ro" 
      # - "/projects/DATASETS/:/usr/share/nginx/html/nsidc-0057:ro" 
      - "/share/logs/noaa-web:/var/log/nginx:rw"
    ports:
      - "80:80"
      - "443:443"
    network_mode: "host"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
