version: '3.4'

services:

  data-server:
    image: "nsidc/noaa-web-server-ingest:${SERVER_VERSION:-latest}"
    volumes:
      - "${STORAGE_DIR}/cogs:/usr/share/nginx/html/cogs:ro"
      - "${STORAGE_DIR}/plots:/usr/share/nginx/html/plots:ro"
      # Mount dynamic legends underneath the static legends dir
      - "${STORAGE_DIR}/dynamic_legends:/usr/share/nginx/html/legends/dynamic:ro"
    ports:
      - "80:80"
      - "443:443"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
