name: noaadata
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python ~=3.10.4

  # Dev dependencies:
  - bump2version ~=1.0
  - invoke ~=1.7
  - black ~=22.3.0
  - isort ~=5.10
  - pytest ~=7.1
  - mypy ~=0.942
  - ipython ~=8.2.0

  - flake8 ~=4.0
  - flake8-bugbear ~=22.3.23
  - flake8-comprehensions ~=3.8
  - flake8-docstrings ~=1.6
  - flake8-use-fstring ~=1.3


  # Runtime dependencies:
  - click ~=8.1
  - satpy ~=0.36.0
  - pyresample ~=1.23
  - pandas ~=1.4
  - geopandas ~=0.10.2
  - rasterio ~=1.1
  - requests ~=2.23
  - shapely ~=1.7
  - numpy ~=1.18
  - luigi ~=3.0
  - apscheduler ~=3.6
  - pyhdf ~=0.10.3
  - sqlalchemy ~=1.3
