#!/bin/bash
set -euo pipefail

ENVIRONMENT="$1"

THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT_DIR="$(dirname "$THIS_DIR")"

VERSION_FILE="$REPO_ROOT_DIR/VERSION.env"

cd "$REPO_ROOT_DIR"

if [ "$ENVIRONMENT" = "integration" ]; then
    version_desc="latest"
    VERSION_FILE="$REPO_ROOT_DIR/VERSION.latest.env"
else
    version_desc="production"
fi

echo "Using $version_desc versions in $ENVIRONMENT..."
cat "$VERSION_FILE"
source "$VERSION_FILE"

# Pull new server version
docker-compose pull

# Cleanup old containers
docker-compose down --remove-orphans

# Start the new server version
docker-compose up -d

# Cleanup old images
docker system prune -af
